import type { WindowConfig } from '../WindowConfig';

export const LeetCodeSolverConfig: WindowConfig = {
  baseSettings: {
    width: 700,
    height: 580,
    minWidth: 500,
    minHeight: 400,
    alwaysOnTop: true,
    show: true,
    fullscreenable: true,
    focusable: true,
    frame: false,
    hasShadow: true,
    transparent: false,
    skipTaskbar: false,
    backgroundColor: '#0f172a',
    type: 'normal',
    paintWhenInitiallyHidden: true,
    movable: true,
    resizable: true,
  },
  behavior: {
    showBehavior: {
      opacity: 1,
      ignoreMouseEvents: false,
      skipTaskbar: false,
      alwaysOnTop: true,
      alwaysOnTopLevel: 'floating',
      visibleOnAllWorkspaces: true,
      visibleOnFullScreen: true,
      focusable: true,
      contentProtection: false,
    },
    hideBehavior: {
      opacity: 0,
      ignoreMouseEvents: true,
      skipTaskbar: false,
      alwaysOnTop: true,
      alwaysOnTopLevel: 'floating',
      visibleOnAllWorkspaces: true,
      visibleOnFullScreen: true,
      focusable: false,
      contentProtection: false,
    },
    queueBehavior: {
      queueEmpty: {
        opacity: 1,
        ignoreMouseEvents: false,
        skipTaskbar: false,
        alwaysOnTop: true,
        alwaysOnTopLevel: 'floating',
        visibleOnAllWorkspaces: true,
        visibleOnFullScreen: true,
        focusable: true,
        contentProtection: false,
      },
      queueWithScreenshots: {
        opacity: 1,
        ignoreMouseEvents: false,
        skipTaskbar: false,
        alwaysOnTop: true,
        alwaysOnTopLevel: 'floating',
        visibleOnAllWorkspaces: true,
        visibleOnFullScreen: true,
        focusable: true,
        contentProtection: false,
      },
    },
    platformSpecific: {
      darwin: {
        hiddenInMissionControl: false,
        windowButtonVisibility: false,
        backgroundColor: '#0f172a',
        hasShadow: true,
      },
      win32: {
        thickFrame: true,
      },
    },
  },
};
