import type { WindowConfig } from '../WindowConfig';

export const LeetCodeSolverConfig: WindowConfig = {
  baseSettings: {
    width: 680,
    height: 540,
    minWidth: 480,
    minHeight: 380,
    alwaysOnTop: true,
    show: true,
    fullscreenable: true,
    focusable: true,
    frame: false,
    hasShadow: false,
    transparent: true,
    skipTaskbar: false,
    backgroundColor: '#00000000',
    type: 'normal',
    paintWhenInitiallyHidden: true,
    movable: true,
    resizable: true,
  },
  behavior: {
    showBehavior: {
      opacity: 1,
      ignoreMouseEvents: false,
      skipTaskbar: false,
      alwaysOnTop: true,
      alwaysOnTopLevel: 'screen-saver',
      visibleOnAllWorkspaces: true,
      visibleOnFullScreen: true,
      focusable: true,
      contentProtection: true,
    },
    hideBehavior: {
      opacity: 0,
      ignoreMouseEvents: true,
      skipTaskbar: false,
      alwaysOnTop: true,
      alwaysOnTopLevel: 'screen-saver',
      visibleOnAllWorkspaces: true,
      visibleOnFullScreen: true,
      focusable: false,
      contentProtection: true,
    },
    queueBehavior: {
      queueEmpty: {
        opacity: 1,
        ignoreMouseEvents: false,
        skipTaskbar: false,
        alwaysOnTop: true,
        alwaysOnTopLevel: 'screen-saver',
        visibleOnAllWorkspaces: true,
        visibleOnFullScreen: true,
        focusable: true,
        contentProtection: true,
      },
      queueWithScreenshots: {
        opacity: 1,
        ignoreMouseEvents: false,
        skipTaskbar: false,
        alwaysOnTop: true,
        alwaysOnTopLevel: 'screen-saver',
        visibleOnAllWorkspaces: true,
        visibleOnFullScreen: true,
        focusable: true,
        contentProtection: true,
      },
    },
    platformSpecific: {
      darwin: {
        hiddenInMissionControl: false,
        windowButtonVisibility: false,
        backgroundColor: '#00000000',
        hasShadow: false,
      },
      win32: {
        thickFrame: false,
      },
    },
  },
};
